### PR TITLE
toward 0.2 release

### PR DESCRIPTION
**Pull request by eracle**
Hi there! Here's some changes toward 0.2 release.

### CODE REVIEW

**Comment by eracle** [comment]
We also have a new logo now, what about the 0.2 release?

**Comment by eracle** [comment]
what you think about this pull request?

**Comment by bashu** [comment]
@eracle I was busy, but I will take care of this and release 0.2 soon...

**Comment by eracle** [comment]
Can we simply merge it? thanks

**Comment by vlinhart** [comment]
Nice work but does it really need to break backward compatibility? (removing `airport_id`). It would also be nice if the airport import was able to update values not just add them. The names of airports get changed and the use of get_object_or_create as is will try to create a new one in case of a change which will fail since the IATA stays the same and is the primary key now. 
 
Maybe this would help:

```python
Airport.objects.update_or_create(iata=iata, icao=icao, defaults=dict(name=name, altitude=altitude, location=point, country=country, city=city))
```
it will update existing and create a new ones.

**Comment by eracle** [comment]
Hello vlinhart,
its true, by removing the airport_id it breaks backward compatibility. 
So maybe we should rename the release as 1.0. I really never understood why the airport is is out there, can be easily replaced with the pk.
About the second point, if you think is a good fix you can propose a PR. @bashu What you think?

**Comment by vlinhart** [comment]
Seems the `airport_id` was there because it was in the source csv as well and to keep the DB and csv in sync easily. 

The migrations proposed here will have to be changed. The IATA can't be a primary key. Looking at the data there are many airports without IATA/ICAO code. So we should probably use the existing airport_id or a new standard auto `id`.

example of no IATA in csv:
`9374,"Susuman Airport","Susuman","Russia",\N,"UHMH",62.766666412353516,148.14666748046875,2129,11,"N","Asia/Srednekolymsk","airport","OurAirports"`

I'd very much welcome the update data on the second run scenario - I'd be happy to do that but it would be better to base it on this PR which is not ok yet.. I'd probably vote for keeping the airport_id, it seems the only reliable data point for the potential update and we'd keep backward compatibility.

**Comment by eracle** [comment]
Ok, @vlinhart, when I have sometime I am going to modify this PR, and also squashing all those commits that is not a good practice to keep them all as such. The problem is that I am not touching this project from 6 months nor using it in production/other stuff, so it is going to be a bit weird handling it again. 
@vlinhart Would you like to contribute somehow? Do you like unit testing? A unit test containing the requested requirements would be nice, and would allow me to understand when the code is ready. Thanks :-)

**Comment by vlinhart** [comment]
@eracle I totally understand. I just got back to a project which uses this and would like to get it uptodate with recent libs and airport DB. So keeping it backwards compatible is important for me but also selfish (preventing it from better design)..

I made a PR to your fork with changes which would suit my project, you can check it out and decide if it's ok for this lib as well. It mostly keeps the changes you've made except airportd_id and updates the DB on subsequent runs.

I've already contributed a small thing 2 years back :-)

**Comment by eracle** [comment]
Just merged @vlinhart's PR. 
Travis Fails with python 3.6. When I have some time I check this out.

**Comment by eracle** [comment]
Ok, after @vlinhart's fix, now it works, also with python3.
@bashu Can you please merge since now it keeps back-compatibility? I reviewed it, and for me is ok!
Awesome work!

**Comment by gabor-boros** [comment]
@eracle & @vlinhart What is the status of this PR?

**Comment by vlinhart** [comment]
I'd say @bashu has no time for it. :cry:

**Comment by vlinhart** [comment]
I'm using the PR version in production for half a year, should be ok...

**Comment by eracle** [comment]
If @bashu allowed us having write access, everything would be easier.

**Comment by vlinhart** [comment]
maybe a fork is in order. It would be awesome to be able to install from pypi. There are some big changes now in the master, I prefer stability. what do you think @eracle ?

**Comment by eracle** [comment]
Hey vlinhart! I am not using this project since more than a year, so I cannot really suggest anything about it. It seems you are the one that was using it in production. The choice is yours. Cheers!

**Comment by vlinhart** [comment]
@eracle Thanks for the nudge. I should have done it long time ago. 
https://pypi.org/project/django-airports-legacy/

**Pull request merged**
